version: '3'
services:
  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    networks:
      - public
    volumes:
      - ./src/main/webapp/picsureui:/usr/local/apache2/htdocs/picsureui
      - ./target/webjars/META-INF/resources/webjars:/usr/local/apache2/htdocs/picsureui/webjars
      - ./src/main/resources:/usr/local/apache2/htdocs/picsureui/settings
networks:
  public:
